"""Auto-generated from TЗ. Vertical -> grade -> list of (code, label)."""
PROFESSIONS = {
    'Gambling': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO', 'Chief Operating Officer'),
            ('CFO', 'Chief Financial Officer'),
            ('CRO', 'Chief Revenue Officer'),
            ('CSO_STRAT', 'Chief Strategy Officer'),
            ('CMO', 'Chief Marketing Officer'),
            ('CCO_COMM', 'Chief Commercial Officer'),
            ('CBDO', 'Chief Business Development Officer'),
            ('CGO_GROWTH', 'Chief Growth Officer'),
            ('CPO_PROD', 'Chief Product Officer'),
            ('CCaO', 'Chief Casino Officer'),
            ('CSBO', 'Chief Sportsbook Officer'),
            ('CGO_GAMES', 'Chief Games Officer'),
            ('CSO_SLOTS', 'Chief Slots Officer'),
            ('CLCO', 'Chief Live Casino Officer'),
            ('CPkO', 'Chief Poker Officer'),
            ('CTO', 'Chief Technology Officer'),
            ('CIO', 'Chief Information Officer'),
            ('CISO', 'Chief Information Security Officer'),
            ('CDO', 'Chief Data Officer'),
            ('CAIO', 'Chief AI Officer'),
            ('CLO', 'Chief Legal Officer'),
            ('CCO_COMP', 'Chief Compliance Officer'),
            ('CRFO', 'Chief Risk & Fraud Officer'),
            ('CRGO', 'Chief Responsible Gambling Officer'),
            ('CPayO', 'Chief Payments Officer'),
            ('CHRO', 'Chief Human Resources Officer'),
            ('CPEO', 'Chief Player Experience Officer'),
        ],
        'Head of / Director': [
            ('DIR_MANAGING', 'Managing Director'),
            ('DIR_OPS', 'Operations Director'),
            ('HEAD_OPS', 'Head of Operations'),
            ('DIR_STRAT', 'Strategy Director'),
            ('DIR_MKT', 'Marketing Director'),
            ('HEAD_MKT', 'Head of Marketing'),
            ('HEAD_AFF', 'Head of Affiliates (Афф-отдел)'),
            ('HEAD_ACQ', 'Head of Acquisition (Закупка)'),
            ('HEAD_MB', 'Head of Media Buying'),
            ('HEAD_SEO', 'Head of SEO'),
            ('DIR_BRAND', 'Brand Director'),
            ('DIR_COMM', 'Commercial Director'),
            ('DIR_BIZDEV', 'Business Development Director'),
            ('HEAD_SALES', 'Head of Sales'),
            ('HEAD_B2B', 'Head of B2B'),
            ('HEAD_AM', 'Head of Account Management'),
            ('DIR_PROD', 'Product Director'),
            ('HEAD_PROD', 'Head of Product'),
            ('HEAD_GAMES', 'Head of Games'),
            ('HEAD_CASINO', 'Head of Casino'),
            ('HEAD_SB', 'Head of Sportsbook (Ставки)'),
            ('HEAD_SLOTS', 'Head of Slots'),
            ('HEAD_LIVE', 'Head of Live Casino'),
            ('HEAD_POKER', 'Head of Poker'),
            ('HEAD_CRM', 'Head of CRM'),
            ('HEAD_RET', 'Head of Retention'),
            ('HEAD_VIP', 'Head of VIP'),
            ('DIR_CX', 'Customer Experience Director'),
            ('HEAD_SUPPORT', 'Head of Customer Support'),
            ('DIR_IT', 'IT Director'),
            ('HEAD_ENG', 'Head of Engineering'),
            ('HEAD_DEV', 'Head of Software Development'),
            ('HEAD_DATA', 'Head of Data & Analytics'),
            ('HEAD_AI', 'Head of AI'),
            ('DIR_LEGAL', 'Legal Director'),
            ('HEAD_COMP', 'Head of Compliance'),
            ('HEAD_RISK', 'Head of Risk & Fraud'),
            ('HEAD_RG', 'Head of Responsible Gambling'),
            ('HEAD_PAY', 'Head of Payments'),
            ('DIR_FIN', 'Finance Director'),
            ('DIR_HR', 'HR Director (Head of People)'),
            ('HEAD_TA', 'Head of Talent Acquisition (Найм)'),
        ],
        'Management': [
            ('MGR_PROJECT', 'Project Manager'),
            ('MGR_PRODUCT', 'Product Manager (Operational)'),
            ('MGR_OPS', 'Operations Manager'),
            ('MGR_DELIVERY', 'Delivery Manager'),
            ('MGR_OFFICE', 'Office Manager / People Ops'),
            ('TL_AFF', 'Affiliate Team Lead'),
            ('TL_MB', 'Media Buying Team Lead'),
            ('TL_SEO', 'SEO Team Lead'),
            ('TL_CRM', 'CRM Team Lead'),
            ('TL_MKT', 'Marketing Team Lead'),
            ('TL_ASO', 'ASO Team Lead'),
            ('TL_SALES', 'Sales Team Lead'),
            ('TL_AM', 'Account Management Team Lead'),
            ('MGR_BD', 'Business Development Manager (Mid)'),
            ('TL_B2B', 'B2B Team Lead'),
            ('TL_DEV', 'Tech Lead / Software Engineering Manager'),
            ('TL_FE', 'Frontend Team Lead'),
            ('TL_BE', 'Backend Team Lead'),
            ('TL_QA', 'QA Team Lead'),
            ('TL_DEVOPS', 'DevOps Team Lead'),
            ('TL_DATA', 'Data Lead / Analytics Lead'),
            ('TL_ARCH', 'Solution Architect'),
            ('MGR_PRODUCER', 'Game Producer'),
            ('TL_ART', 'Art Lead / Creative Lead'),
            ('TL_DESIGN', 'Design Team Lead / Lead UI/UX'),
            ('MGR_LOC', 'Localization Manager'),
            ('TL_CONTENT', 'Content Team Lead'),
            ('TL_SUPPORT', 'Support Team Lead'),
            ('TL_VIP', 'VIP Team Lead'),
            ('TL_FRAUD', 'Fraud Team Lead'),
            ('TL_RISK', 'Risk Team Lead'),
            ('TL_COMP', 'Compliance Manager'),
        ],
        'Senior': [
            ('SNR_MB_FB', 'Senior Media Buyer (Facebook/Meta)'),
            ('SNR_MB_GG', 'Senior Media Buyer (Google Ads)'),
            ('SNR_MB_TT', 'Senior Media Buyer (TikTok)'),
            ('SNR_AFF', 'Senior Affiliate Manager'),
            ('SNR_SEO_TECH', 'Senior Technical SEO Specialist'),
            ('SNR_ASO', 'Senior ASO Specialist (App Store Optimization)'),
            ('SNR_GAME_DESIGN', 'Senior Game Designer (iGaming)'),
            ('SNR_MATH', 'Senior Slot Mathematician (RNG/Математик)'),
            ('SNR_UIUX', 'Senior Product Designer (UI/UX)'),
            ('SNR_ECONOMIST', 'Senior Game Economist (Tokenomics/Economy)'),
            ('SNR_COPY', 'Senior UX Copywriter (Gambling/Betting)'),
            ('SNR_BE_PHP', 'Senior Backend Developer (PHP/Laravel)'),
            ('SNR_BE_GO', 'Senior Backend Developer (Go)'),
            ('SNR_FE_REACT', 'Senior Frontend Developer (React/Vue)'),
            ('SNR_BLOCKCHAIN', 'Senior Solidity/Blockchain Developer (для Crypto Casinos)'),
            ('SNR_DEVOPS', 'Senior DevOps Engineer'),
            ('SNR_SEC', 'Senior Cybersecurity Engineer'),
            ('SNR_CRM', 'Senior CRM Manager (Retention)'),
            ('SNR_VIP', 'Senior VIP Manager (High Rollers)'),
            ('SNR_RET', 'Senior Retention Specialist'),
            ('SNR_PAY', 'Senior Payments Analyst'),
            ('SNR_TRADER', 'Senior Sports Trader (для Букмекеров/Sportsbook)'),
            ('SNR_DATA_ANALYST', 'Senior Data Analyst'),
            ('SNR_BI', 'Senior BI Analyst (Business Intelligence)'),
            ('SNR_ML', 'Senior ML Engineer (Anti-fraud/Personalization)'),
            ('SNR_BD', 'Senior Business Development Executive'),
            ('SNR_AM', 'Senior Account Manager (B2B)'),
            ('SNR_FRAUD', 'Senior Fraud / Risk Analyst'),
            ('SNR_COMP', 'Senior Compliance Officer (Licensing)'),
        ],
        'Specialist': [
            ('SPEC_AFF', 'Affiliate Manager'),
            ('SPEC_MB', 'Media Buyer (Universal)'),
            ('SPEC_SEO', 'SEO Specialist'),
            ('SPEC_ASO', 'ASO Specialist'),
            ('SPEC_INFL', 'Influencer Manager'),
            ('SPEC_SMM', 'SMM Specialist (iGaming)'),
            ('SPEC_EMAIL', 'Email Marketing Specialist'),
            ('SPEC_COMP', 'Compliance Officer (Licensing)'),
            ('SPEC_AML', 'AML Specialist (Anti-Money Laundering)'),
            ('SPEC_RG', 'Responsible Gambling Specialist'),
            ('SPEC_FRAUD', 'Fraud / Risk Analyst'),
            ('SPEC_PAY', 'Payments Specialist'),
            ('SPEC_VIP_HOST', 'VIP Host / VIP Account Manager'),
            ('SPEC_RET', 'Retention Manager / CRM Specialist'),
            ('SPEC_SUPPORT', 'Customer Support Specialist'),
            ('SPEC_TRADER', 'Sports Trader (Live/Prematch)'),
            ('SPEC_MATH', 'Game Mathematician (RNG)'),
            ('SPEC_DATA', 'Data Analyst (LTV/GGR)'),
            ('SPEC_DEV_FE', 'Frontend Developer'),
            ('SPEC_DEV_BE', 'Backend Developer'),
            ('SPEC_QA', 'QA Engineer (Manual/Auto)'),
            ('SPEC_DESIGN', 'UI/UX Designer'),
            ('SPEC_ART', '2D/3D Artist (Slots/Games)'),
            ('SPEC_LOC', 'Localization Specialist (iGaming)'),
            ('SPEC_COPY', 'Content Writer / Copywriter'),
            ('SPEC_AM_B2B', 'Account Manager (B2B)'),
            ('SPEC_PAY_AM', 'Payment Account Manager'),
            ('SPEC_SALES', 'Sales Executive'),
            ('SPEC_BD', 'Business Development Executive'),
            ('SPEC_RECRUITER', 'iGaming Recruiter'),
            ('SPEC_FIN', 'Accountant (iGaming/Crypto)'),
        ],
        'Junior / Entry': [
            ('JUN_AFF', 'Junior Affiliate Manager'),
            ('JUN_MB', 'Junior Media Buyer'),
            ('JUN_FARMER', 'Account Farmer (Meta/Google)'),
            ('JUN_LINK', 'Linkbuilder — Основа для SEO команд'),
            ('JUN_SEO', 'Junior SEO Specialist'),
            ('JUN_SMM', 'Junior SMM / Community Manager'),
            ('JUN_SUPPORT', 'Support Agent (Tier 1 / Chat)'),
            ('JUN_FRAUD', 'Junior Fraud Analyst'),
            ('JUN_PAY', 'Junior Payments Specialist'),
            ('JUN_MODERATOR', 'Content Moderator (Gambling)'),
            ('JUN_CRM', 'Junior CRM / Email Marketer'),
            ('JUN_DEV', 'Junior Developer (Frontend/Backend)'),
            ('JUN_QA', 'Junior QA Tester (Manual)'),
            ('JUN_DESIGN', 'Junior Designer / Graphic Designer'),
            ('JUN_CONTENT', 'Content Administrator / Uploader'),
            ('JUN_COPY', 'Junior Copywriter / Rewriter'),
            ('JUN_SALES', 'Junior Sales Executive'),
            ('JUN_BD', 'Business Development Assistant'),
            ('JUN_RECRUITER', 'Recruiting Coordinator / Junior Recruiter'),
            ('JUN_ADMIN', 'Administrative Assistant / Office Junior'),
        ],
    },
    'Betting': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO', 'Chief Operations Officer'),
            ('CFO', 'Chief Financial Officer'),
            ('CRO', 'Chief Revenue Officer'),
            ('CSO', 'Chief Strategy Officer'),
            ('CMO', 'Chief Marketing Officer'),
            ('CCO', 'Chief Commercial Officer'),
            ('CBDO', 'Chief Business Development Officer'),
            ('CGO', 'Chief Growth Officer'),
            ('CSBO', 'Chief Sportsbook Officer'),
            ('CTrO', 'Chief Trading Officer'),
            ('CPO', 'Chief Product Officer'),
            ('CGO_GAMES', 'Chief Games Officer'),
            ('CTO', 'Chief Technology Officer'),
            ('CIO', 'Chief Information Officer'),
            ('CISO', 'Chief Information Security Officer'),
            ('CDO', 'Chief Data Officer'),
            ('CAIO', 'Chief AI Officer'),
            ('CLO', 'Chief Legal Officer'),
            ('CCAO', 'Chief Corporate Affairs Officer'),
            ('CCO_COMP', 'Chief Compliance Officer'),
            ('CRFO', 'Chief Risk & Fraud Officer'),
            ('CRGO', 'Chief Responsible Gambling Officer'),
            ('CPayO', 'Chief Payments Officer'),
            ('CHRO', 'Chief Human Resources Officer'),
            ('CPEO', 'Chief Player Experience Officer'),
        ],
        'Head of / Director': [
            ('DIR_MANAGING', 'Managing Director'),
            ('DIR_OPS', 'Operations Director'),
            ('HEAD_OPS', 'Head of Operations'),
            ('DIR_STRAT', 'Strategy Director'),
            ('HEAD_TRADING', 'Head of Trading'),
            ('DIR_TRADING', 'Director of Trading'),
            ('HEAD_RISK', 'Head of Sportsbook Risk'),
            ('HEAD_INTEGRITY', 'Head of Sports Integrity'),
            ('DIR_MKT', 'Marketing Director (Betting)'),
            ('HEAD_MKT', 'Head of Marketing'),
            ('HEAD_AFF_BET', 'Head of Affiliates'),
            ('HEAD_ACQ', 'Head of Acquisition'),
            ('HEAD_MB', 'Head of Media Buying'),
            ('HEAD_SEO', 'Head of SEO'),
            ('DIR_BRAND', 'Brand Director'),
            ('DIR_COMM', 'Commercial Director'),
            ('DIR_BIZDEV', 'Business Development Director'),
            ('HEAD_SALES', 'Head of Sales'),
            ('HEAD_AM', 'Head of Account Management (B2B)'),
            ('DIR_PROD', 'Product Director (Sportsbook)'),
            ('HEAD_PROD', 'Head of Product'),
            ('HEAD_CRM_RET', 'Head of CRM & Retention'),
            ('HEAD_VIP_BET', 'Head of VIP (Betting)'),
            ('HEAD_SUPPORT', 'Head of Customer Support'),
            ('DIR_IT', 'IT Director'),
            ('HEAD_ENG', 'Head of Engineering'),
            ('HEAD_DATA', 'Head of Data & Analytics'),
            ('HEAD_AI_BET', 'Head of AI / Modeling'),
            ('DIR_LEGAL', 'Legal Director'),
            ('HEAD_COMP', 'Head of Compliance'),
            ('HEAD_AML_FRAUD', 'Head of AML & Anti-Fraud'),
            ('HEAD_RG', 'Head of Responsible Gambling'),
            ('HEAD_PAY_BET', 'Head of Payments'),
            ('DIR_HR', 'HR Director / Head of People'),
            ('HEAD_TA', 'Head of Talent Acquisition'),
        ],
        'Management': [
            ('TL_TRADER', 'Trading Team Lead'),
            ('MGR_EVENTS', 'Sports Events Manager'),
            ('MGR_LIABILITY', 'Liability Manager'),
            ('TL_ODDS', 'Odds Management Lead'),
            ('TL_AFF_BET', 'Affiliate Team Lead (Betting)'),
            ('TL_MB_SPORTS', 'Media Buying Team Lead (Sports)'),
            ('TL_SEO_BET', 'SEO Team Lead (Betting)'),
            ('TL_CRM_BET', 'CRM Team Lead (Betting)'),
            ('TL_ASO_BET', 'ASO Team Lead'),
            ('MGR_PROD_SB', 'Product Manager (Sportsbook)'),
            ('MGR_PROJ_SB', 'Project Manager (Sportsbook)'),
            ('MGR_DELIVERY', 'Delivery Manager'),
            ('MGR_OPS_BET', 'Operations Manager'),
            ('TL_DEV_BET', 'Tech Lead (Sportsbook Development)'),
            ('TL_QA_BET', 'QA Team Lead (Betting Engine)'),
            ('TL_DATA_BET', 'Data Lead / Analytics Lead'),
            ('TL_ARCH_BET', 'Solution Architect (Betting)'),
            ('TL_SUPPORT_BET', 'Support Team Lead (Sportsbook)'),
            ('TL_VIP_BET', 'VIP Team Lead (Betting)'),
            ('TL_FRAUD_BET', 'Fraud Team Lead (Sports/Betting)'),
            ('TL_RISK_BET', 'Risk Team Lead (Sportsbook)'),
            ('MGR_COMP_BET', 'Compliance Manager'),
        ],
        'Senior': [
            ('SNR_TRADER_BET', 'Senior Sports Trader'),
            ('SNR_ODDS_COMP', 'Senior Odds Compiler'),
            ('SNR_QUANT_ANALYST', 'Senior Quantitative Analyst'),
            ('SNR_BET_ANALYST', 'Senior Betting Analyst'),
            ('SNR_RISK_SPORTS', 'Senior Sports Risk Analyst'),
            ('SNR_MB_SPORTS', 'Senior Media Buyer (Sports)'),
            ('SNR_AFF_BET', 'Senior Affiliate Manager (Betting)'),
            ('SNR_PARTNERSHIP', 'Senior Partnership Manager'),
            ('SNR_SEO_BET', 'Senior SEO Specialist'),
            ('SNR_ASO_BET', 'Senior ASO Specialist (Betting Apps)'),
            ('SNR_DEV_ENGINE', 'Senior Backend Developer (High-load / Betting Engine)'),
            ('SNR_DEV_LIVE', 'Senior Frontend Developer (Live Data / Real-time Odds)'),
            ('SNR_DATA_SCI', 'Senior Data Scientist (Modeling probabilities)'),
            ('SNR_QA_BET', 'Senior QA Engineer (Betting Systems)'),
            ('SNR_VIP_BET', 'Senior VIP Manager (High Rollers)'),
            ('SNR_CRM_BET', 'Senior CRM Specialist (Retention)'),
            ('SNR_PAY_BET', 'Senior Payments Analyst'),
            ('SNR_FRAUD_BET', 'Senior Fraud Analyst (Sports Integrity)'),
            ('SNR_COMP_BET', 'Senior Compliance Officer (Licensing)'),
        ],
        'Specialist': [
            ('SPEC_TRADER_LIVE', 'Live Trader'),
            ('SPEC_TRADER_PRE', 'Pre-match Trader'),
            ('SPEC_RISK_ANALYST', 'Sports Risk Analyst'),
            ('SPEC_ODDS_TECH', 'Odds Specialist'),
            ('SPEC_AFF_BET', 'Affiliate Manager (Betting)'),
            ('SPEC_MB_BET', 'Media Buyer (Sports Traffic)'),
            ('SPEC_SEO_BET', 'SEO Specialist'),
            ('SPEC_ASO_BET', 'ASO Specialist'),
            ('SPEC_INFL_BET', 'Influencer Manager'),
            ('SPEC_CRM_BET', 'CRM Specialist (Retention)'),
            ('SPEC_VIP_HOST', 'VIP Account Manager'),
            ('SPEC_TIPSTER', 'Sports Tipster / Analyst'),
            ('SPEC_COPY_BET', 'Sports Copywriter'),
            ('SPEC_PROD_SB', 'Sportsbook Product Specialist'),
            ('SPEC_FRAUD_BET', 'Fraud Analyst (Sportsbook)'),
            ('SPEC_PAY_BET', 'Payments Specialist'),
            ('SPEC_COMP_BET', 'Compliance Officer'),
            ('SPEC_AML_KYC', 'AML / KYC Specialist'),
            ('SPEC_DEV_FE', 'Frontend Developer'),
            ('SPEC_DEV_BE', 'Backend Developer'),
            ('SPEC_QA_BET', 'QA Engineer (Manual/Auto)'),
            ('SPEC_DATA_BET', 'Data Analyst (GGR/NGR/LTV)'),
        ],
        'Junior / Entry': [
            ('JUN_TRADER', 'Junior Sports Trader'),
            ('JUN_ODDS_MON', 'Odds Monitor'),
            ('JUN_RESULT_AGENT', 'Resulting Agent'),
            ('JUN_DATA_ENTRY', 'Data Entry Specialist'),
            ('JUN_AFF_BET', 'Junior Affiliate Manager'),
            ('JUN_MB_BET', 'Junior Media Buyer'),
            ('JUN_FARMER_BET', 'Account Farmer (Meta/Google/TikTok)'),
            ('JUN_LINK_BET', 'Linkbuilder (SEO Betting)'),
            ('JUN_SEO_ASO', 'Junior SEO / ASO Assistant'),
            ('JUN_SUPPORT_BET', 'Sportsbook Support Agent'),
            ('JUN_FRAUD_ANALYST', 'Junior Fraud / Risk Analyst'),
            ('JUN_KYC_BET', 'Junior KYC / Verification Officer'),
            ('JUN_PAY_ADMIN', 'Junior Payments Administrator'),
            ('JUN_COPY_SPORTS', 'Junior Sports Copywriter'),
            ('JUN_SOCIAL_MOD', 'Social Media Moderator'),
            ('JUN_DESIGN_JUN', 'Junior Graphic Designer'),
            ('JUN_RECRUITER', 'Recruiting Coordinator'),
            ('JUN_ADMIN_OFFICE', 'Office Assistant / Junior Admin'),
        ],
    },
    'Crypto': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO', 'Chief Operating Officer'),
            ('CFO_CRYPTO', 'Chief Financial Officer'),
            ('CSO_WEB3', 'Chief Strategy Officer'),
            ('CTO_WEB3', 'Chief Technology Officer (Blockchain / Web3 Infrastructure)'),
            ('CISO_CRYPTO', 'Chief Information Security Officer'),
            ('CDO_WEB3', 'Chief Data Officer'),
            ('CTO_INFRA', 'Chief Infrastructure Officer'),
            ('CBDO_CRYPTO', 'Chief Business Development Officer'),
            ('CMO_WEB3', 'Chief Marketing Officer'),
            ('CGO_CRYPTO', 'Chief Growth Officer'),
            ('CEOs_OFFICER', 'Chief Ecosystem Officer'),
            ('CPO_WEB3', 'Chief Product Officer (DeFi / DEX / Wallet / NFT Platforms)'),
            ('CTOkO', 'Chief Tokenomics Officer'),
            ('CIO_CRYPTO', 'Chief Investment Officer'),
            ('CHIO', 'Chief Innovation Officer'),
            ('CLO_CRYPTO', 'Chief Legal Officer (VASP / MiCA / SEC Compliance)'),
            ('CCO_AML', 'Chief Compliance Officer'),
            ('CRiO_CRYPTO', 'Chief Risk Officer'),
            ('CGovO', 'Chief Governance Officer'),
        ],
        'Head of / Director': [
            ('DIR_OPS_CRYPTO', 'Operations Director'),
            ('HEAD_STRAT_WEB3', 'Head of Strategy'),
            ('DIR_ECOSYSTEM', 'Director of Ecosystem'),
            ('HEAD_GOVERNANCE', 'Head of Governance (DAO)'),
            ('DIR_MKT_WEB3', 'Marketing Director (Web3 focus)'),
            ('HEAD_COMMUNITY', 'Head of Community'),
            ('HEAD_PR_WEB3', 'Head of PR & Communications'),
            ('HEAD_GROWTH_CRYPTO', 'Head of Growth'),
            ('HEAD_KOL_RELATIONS', 'Head of Influencer Marketing'),
            ('DIR_PROD_CRYPTO', 'Product Director (CEX/DEX/Wallet/DApps)'),
            ('HEAD_TOKENOMICS', 'Head of Tokenomics'),
            ('HEAD_LISTING', 'Head of Listing'),
            ('HEAD_LIQUIDITY', 'Head of Liquidity & Market Making'),
            ('HEAD_BD_CRYPTO', 'Head of Business Development'),
            ('DIR_PARTNERSHIPS', 'Director of Partnerships'),
            ('HEAD_INSTITUTIONAL', 'Head of Institutional Sales'),
            ('HEAD_INVESTOR_REL', 'Head of Investor Relations'),
            ('HEAD_ENG_BLOCKCHAIN', 'Head of Blockchain Engineering'),
            ('DIR_TECH_INFRA', 'Director of Crypto Infrastructure (Nodes/Staking/Validation)'),
            ('HEAD_SECURITY_AUDIT', 'Head of Security & Smart Contract Audit'),
            ('HEAD_DATA_WEB3', 'Head of Data Science (On-chain analysis)'),
            ('DIR_LEGAL_CRYPTO', 'Legal Director (Global Crypto Regulation)'),
            ('HEAD_COMP_VASP', 'Head of Compliance (AML/VASP/MiCA)'),
            ('HEAD_TREASURY', 'Head of Treasury'),
            ('DIR_FIN_CRYPTO', 'Finance Director'),
        ],
        'Management': [
            ('TL_BLOCKCHAIN', 'Tech Lead (Blockchain / Solidity / Rust)'),
            ('TL_SMART_AUDIT', 'Smart Contract Audit Lead'),
            ('MGR_PROD_WEB3', 'Product Manager (Web3 / DeFi / NFT)'),
            ('MGR_PROJ_CRYPTO', 'Project Manager (Web3)'),
            ('TL_QA_CRYPTO', 'QA Team Lead (DApps / Protocol Testing)'),
            ('MGR_DAO', 'DAO Operations Manager'),
            ('TL_COMMUNITY', 'Community Team Lead'),
            ('MGR_SOCIAL_WEB3', 'Social Media Manager'),
            ('TL_MODERATION', 'Moderation Team Lead'),
            ('MGR_EVENTS_WEB3', 'Web3 Event Manager'),
            ('MGR_LISTING', 'Listing Manager'),
            ('MGR_BD_WEB3', 'Business Development Manager'),
            ('TL_AM_CRYPTO', 'Account Management Lead'),
            ('MGR_PARTNERSHIP', 'Partnership Manager'),
            ('TL_MB_CRYPTO', 'Media Buying Team Lead'),
            ('TL_AFF_CRYPTO', 'Affiliate Team Lead'),
            ('MGR_KOL_RELATIONS', 'KOL Relations Manager'),
            ('MGR_GROWTH_WEB3', 'Growth Manager (Web3 Growth Hacking)'),
            ('TL_AML_KYC', 'AML / KYC Team Lead'),
            ('TL_SUPPORT_CRYPTO', 'Customer Support Lead (Exchange / Wallet Support)'),
            ('MGR_SECURITY_OPS', 'Security Operations Manager (SecOps)'),
        ],
        'Senior': [
            ('SNR_SOLIDITY_DEV', 'Senior Solidity Developer'),
            ('SNR_RUST_DEV', 'Senior Rust Developer'),
            ('SNR_BLOCKCHAIN_ARCH', 'Senior Blockchain Architect'),
            ('SNR_ZK_ENGINEER', 'Senior ZK-Proof Engineer'),
            ('SNR_CRYPTOGRAPHER', 'Senior Cryptographer'),
            ('SNR_SMART_AUDITOR', 'Senior Smart Contract Auditor'),
            ('SNR_WEB3_SECURITY', 'Senior Web3 Security Specialist'),
            ('SNR_SEC_RESEARCH', 'Senior Security Researcher'),
            ('SNR_TOKENOMICS_EXPERT', 'Senior Tokenomics Expert'),
            ('SNR_QUANT_CRYPTO', 'Senior Quantitative Analyst'),
            ('SNR_ONCHAIN_ANALYST', 'Senior On-chain Data Analyst'),
            ('SNR_DEFI_ANALYST', 'Senior DeFi Strategist'),
            ('SNR_CRYPTO_MB', 'Senior Media Buyer (Crypto-native / Twitter / Google)'),
            ('SNR_GLOBAL_COMMUNITY', 'Senior Global Community Manager'),
            ('SNR_CONTENT_STRAT', 'Senior Web3 Content Strategist'),
            ('SNR_AFF_CRYPTO', 'Senior Affiliate Manager (Crypto/Web3)'),
            ('SNR_PROD_WEB3', 'Senior Product Manager (Wallet / DEX / Protocol)'),
            ('SNR_UIUX_WEB3', 'Senior Web3 Product Designer'),
            ('SNR_UX_RESEARCH', 'Senior UX Researcher (Web3 focus)'),
            ('SNR_CRYPTO_COMP', 'Senior Compliance Officer (AML/VASP/MiCA)'),
            ('SNR_LEGAL_COUNSEL', 'Senior Crypto Legal Counsel'),
            ('SNR_TREASURY_ANALYST', 'Senior Treasury Analyst'),
        ],
        'Specialist': [
            ('SPEC_SOLIDITY_DEV', 'Solidity Developer'),
            ('SPEC_RUST_DEV', 'Rust Developer'),
            ('SPEC_WEB3_FRONT', 'Web3 Frontend Developer'),
            ('SPEC_QA_BLOCKCHAIN', 'Blockchain QA Engineer'),
            ('SPEC_INFRA_NODE', 'Node Operator / Infrastructure Specialist'),
            ('SPEC_COMMUNITY_MGR', 'Community Manager'),
            ('SPEC_SMM_CRYPTO', 'Crypto SMM Specialist'),
            ('SPEC_CONTENT_WRITER', 'Web3 Content Writer'),
            ('SPEC_MODERATOR_T2', 'Senior Moderator'),
            ('SPEC_AFF_CRYPTO', 'Affiliate Manager (Crypto)'),
            ('SPEC_MB_CRYPTO', 'Media Buyer (Crypto Ads)'),
            ('SPEC_INFLUENCER_MGR', 'KOL / Influencer Manager'),
            ('SPEC_SEO_CRYPTO', 'Crypto SEO Specialist'),
            ('SPEC_LISTING_CORD', 'Listing Coordinator'),
            ('SPEC_TOKENOMICS_ANALYST', 'Tokenomics Analyst'),
            ('SPEC_DATA_WEB3', 'On-chain Data Analyst'),
            ('SPEC_MARKET_MAKER', 'Junior Market Maker / Trader'),
            ('SPEC_UIUX_WEB3', 'Web3 UI/UX Designer'),
            ('SPEC_GRAPHIC_CRYPTO', 'Graphic Designer (Crypto)'),
            ('SPEC_AML_KYC', 'AML / KYC Specialist'),
            ('SPEC_FRAUD_ANALYST', 'Fraud Analyst (Crypto)'),
            ('SPEC_SUPPORT_EXCHANGE', 'Support Specialist'),
        ],
        'Junior / Entry': [
            ('JUN_MODERATOR_DISCORD', 'Discord / TG Moderator'),
            ('JUN_COMMUNITY_HELPER', 'Community Helper'),
            ('JUN_SOCIAL_ASSISTANT', 'Social Media Assistant'),
            ('JUN_AMBASSADOR_COORD', 'Ambassador Coordinator'),
            ('JUN_MB_CRYPTO', 'Junior Media Buyer (Crypto)'),
            ('JUN_AFF_CRYPTO', 'Junior Affiliate Manager (Crypto)'),
            ('JUN_FARMER_SOCIAL', 'Social Account Farmer'),
            ('JUN_INFLUENCER_SCOUT', 'KOL Scout'),
            ('JUN_DEV_WEB3', 'Junior Blockchain Developer'),
            ('JUN_QA_WEB3', 'Junior Web3 Tester'),
            ('JUN_DEV_FRONT_WEB3', 'Junior Frontend (Web3)'),
            ('JUN_CRYPTO_RESEARCH', 'Junior Research Analyst'),
            ('JUN_DATA_ENTRY_WEB3', 'Data Entry Specialist'),
            ('JUN_AIRDROP_HUNTER', 'Retrodrop / Airdrop Specialist'),
            ('JUN_SUPPORT_CRYPTO', 'Customer Support Agent'),
            ('JUN_KYC_OFFICER', 'Junior KYC Analyst'),
            ('JUN_FRAUD_MONITOR', 'Junior Fraud Monitor'),
        ],
    },
    'Dating': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO', 'Chief Operating Officer'),
            ('CFO', 'Chief Financial Officer'),
            ('CSO', 'Chief Strategy Officer'),
            ('CMO', 'Chief Marketing Officer'),
            ('CGO', 'Chief Growth Officer'),
            ('CRO_DATING', 'Chief Revenue Officer'),
            ('CBDO_DATING', 'Chief Business Development Officer'),
            ('CPO_DATING', 'Chief Product Officer'),
            ('CTO_DATING', 'Chief Technology Officer'),
            ('CDO_DATING', 'Chief Data Officer'),
            ('CIO_DATING', 'Chief Innovation Officer (AI-мэтчинг и нейросети)'),
            ('CLO_DATING', 'Chief Legal Officer'),
            ('CSafeO', 'Chief Safety Officer'),
            ('CPayO_DATING', 'Chief Payments Officer'),
        ],
        'Head of / Director': [
            ('DIR_MANAGING', 'Managing Director'),
            ('DIR_OPS_DATING', 'Operations Director'),
            ('HEAD_OPS', 'Head of Operations'),
            ('DIR_STRAT', 'Strategy Director'),
            ('HEAD_UA_MOBILE', 'Head of Mobile Acquisition'),
            ('HEAD_AFF_DATING', 'Head of Affiliates (Dating)'),
            ('HEAD_MB_DATING', 'Head of Media Buying'),
            ('HEAD_ASO_DATING', 'Head of ASO'),
            ('HEAD_SEO_DATING', 'Head of SEO'),
            ('DIR_MKT_DATING', 'Marketing Director'),
            ('DIR_PROD_DATING', 'Product Director'),
            ('HEAD_PROD_DATING', 'Head of Product'),
            ('HEAD_GROWTH', 'Head of Growth'),
            ('HEAD_MONETIZATION', 'Head of Monetization'),
            ('HEAD_CRM_RET', 'Head of CRM & Retention'),
            ('HEAD_MODERATION', 'Head of Content Moderation'),
            ('HEAD_TRUST_SAFETY', 'Head of Trust & Safety'),
            ('HEAD_ANTIFRAUD', 'Head of Anti-Fraud / Verification'),
            ('DIR_COMM', 'Commercial Director'),
            ('HEAD_BD_DATING', 'Head of Business Development'),
            ('HEAD_PARTNERSHIPS', 'Head of Partnerships (OEM/Pre-installs)'),
            ('DIR_IT', 'IT Director'),
            ('HEAD_ENG', 'Head of Engineering'),
            ('HEAD_DATA_DATING', 'Head of Data Science'),
            ('HEAD_AI_MATCHING', 'Head of AI / ML'),
            ('HEAD_LEGAL', 'Head of Legal'),
            ('HEAD_COMP_DATING', 'Head of Compliance (GDPR/Privacy)'),
            ('HEAD_PAY_DATING', 'Head of Payments / Billing'),
            ('DIR_HR', 'HR Director / Head of People'),
            ('HEAD_TA', 'Head of Talent Acquisition'),
        ],
        'Management': [
            ('TL_MB_DATING', 'Media Buying Team Lead'),
            ('TL_AFF_DATING', 'Affiliate Team Lead'),
            ('TL_ASO_DATING', 'ASO Team Lead'),
            ('TL_UA_DATING', 'User Acquisition Lead'),
            ('MGR_INFLUENCER', 'Influencer Marketing Manager'),
            ('MGR_PROD_DATING', 'Product Manager'),
            ('MGR_CRM_DATING', 'CRM Manager'),
            ('MGR_GROWTH_DATING', 'Growth Manager'),
            ('TL_CREATIVE', 'Creative Team Lead'),
            ('TL_MODERATION', 'Moderation Team Lead'),
            ('MGR_OPS_DATING', 'Operations Manager'),
            ('MGR_ANTI_FRAUD', 'Anti-Fraud Manager'),
            ('MGR_BILLING', 'Billing Manager'),
            ('TL_MOBILE_DEV', 'Mobile Tech Lead'),
            ('TL_BACKEND', 'Backend Tech Lead'),
            ('TL_QA_DATING', 'QA Team Lead'),
            ('TL_DATA_DATING', 'Data Lead'),
            ('MGR_BD_DATING', 'Business Development Manager'),
            ('TL_SUPPORT_DATING', 'Support Team Lead'),
            ('TL_AM_DATING', 'Account Management Lead'),
        ],
        'Senior': [
            ('SNR_MB_DATING', 'Senior Media Buyer'),
            ('SNR_ASO_DATING', 'Senior ASO Specialist'),
            ('SNR_AFF_DATING', 'Senior Affiliate Manager'),
            ('SNR_SEO_DATING', 'Senior SEO Specialist'),
            ('SNR_UA_MOBILE', 'Senior User Acquisition Manager'),
            ('SNR_PROD_DATING', 'Senior Product Manager'),
            ('SNR_CRM_DATING', 'Senior CRM Specialist'),
            ('SNR_GROWTH_HACK', 'Senior Growth Hacker'),
            ('SNR_MONETIZATION', 'Senior Monetization Specialist'),
            ('SNR_MOBILE_DEV', 'Senior Mobile Developer'),
            ('SNR_BACKEND_DATING', 'Senior Backend Developer'),
            ('SNR_DATA_SCI_DATING', 'Senior Data Scientist'),
            ('SNR_QA_AUTO_DATING', 'Senior QA Automation'),
            ('SNR_MODERATOR_DATING', 'Senior Content Moderator'),
            ('SNR_FRAUD_ANALYST', 'Senior Anti-Fraud Analyst'),
            ('SNR_COMP_DATING', 'Senior Compliance Officer'),
            ('SNR_UXUI_DATING', 'Senior Product Designer'),
            ('SNR_MOTION_DATING', 'Senior Motion Designer'),
            ('SNR_COPY_DATING', 'Senior Conversion Copywriter'),
        ],
        'Specialist': [
            ('SPEC_MB_DATING', 'Media Buyer'),
            ('SPEC_AFF_DATING', 'Affiliate Manager'),
            ('SPEC_ASO_DATING', 'ASO Specialist'),
            ('SPEC_SEO_DATING', 'SEO Specialist'),
            ('SPEC_UA_MOBILE', 'User Acquisition Specialist'),
            ('SPEC_PROD_DATING', 'Product Manager'),
            ('SPEC_CRM_DATING', 'CRM Specialist'),
            ('SPEC_GROWTH_MKT', 'Growth Marketing Specialist'),
            ('SPEC_RETENTION_MGR', 'Retention Manager'),
            ('SPEC_MODERATOR', 'Content Moderator (Safety)'),
            ('SPEC_FRAUD_ANALYST', 'Anti-Fraud Specialist'),
            ('SPEC_SUPPORT_DATING', 'Customer Support Specialist'),
            ('SPEC_VERIFICATION', 'Verification Specialist'),
            ('SPEC_IOS_DEV', 'iOS Developer'),
            ('SPEC_ANDROID_DEV', 'Android Developer'),
            ('SPEC_BACKEND_DEV', 'Backend Developer'),
            ('SPEC_QA_DATING', 'QA Engineer'),
            ('SPEC_DATA_ANALYST', 'Data Analyst'),
            ('SPEC_UIUX_DESIGN', 'UI/UX Designer'),
            ('SPEC_CREATIVE_DESIGN', 'Creative Designer'),
            ('SPEC_COPY_DATING', 'Copywriter'),
        ],
        'Junior / Entry': [
            ('JUN_MB_DATING', 'Junior Media Buyer'),
            ('JUN_AFF_DATING', 'Junior Affiliate Manager'),
            ('JUN_FARMER_DATING', 'Account Farmer'),
            ('JUN_ASO_ASST', 'Junior ASO Assistant'),
            ('JUN_SEO_LINK', 'Linkbuilder / Junior SEO'),
            ('JUN_MODERATOR', 'Junior Content Moderator'),
            ('JUN_FRAUD_MONITOR', 'Junior Anti-Fraud Monitor'),
            ('JUN_VERIF_OFFICER', 'Verification Assistant'),
            ('JUN_DATA_ENTRY', 'Data Entry Specialist'),
            ('JUN_CRM_DATING', 'Junior CRM Manager'),
            ('JUN_CONTENT_MGR', 'Junior Content Manager'),
            ('JUN_MARKET_RES', 'Market Research Assistant'),
            ('JUN_SUPPORT_DATING', 'Support Agent'),
            ('JUN_QA_MOBILE', 'Junior QA Tester'),
            ('JUN_DESIGN_JUN', 'Junior Graphic Designer'),
            ('JUN_DEV_DATING', 'Junior Developer'),
        ],
    },
    'E-Commerce': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO', 'Chief Operating Officer'),
            ('CFO', 'Chief Financial Officer'),
            ('CSO', 'Chief Strategy Officer'),
            ('CMO', 'Chief Marketing Officer'),
            ('CGO', 'Chief Growth Officer'),
            ('CRO_ECOM', 'Chief Revenue Officer'),
            ('CBDO_ECOM', 'Chief Business Development Officer'),
            ('CSCO', 'Chief Supply Chain Officer'),
            ('CLO_LOG', 'Chief Logistics Officer'),
            ('CPO_SUPPLY', 'Chief Procurement Officer'),
            ('CPO_ECOM', 'Chief Product Officer'),
            ('CTO_ECOM', 'Chief Technology Officer'),
            ('CDO_ECOM', 'Chief Digital Officer'),
            ('CISO_ECOM', 'Chief Information Security Officer'),
            ('CLO', 'Chief Legal Officer'),
            ('CHRO', 'Chief Human Resources Officer'),
            ('CXO', 'Chief Experience Officer'),
        ],
        'Head of / Director': [
            ('HEAD_LOGISTICS', 'Head of Logistics'),
            ('DIR_SUPPLY_CHAIN', 'Director of Supply Chain'),
            ('HEAD_FULFILLMENT', 'Head of Fulfillment'),
            ('HEAD_LAST_MILE', 'Head of Last Mile'),
            ('DIR_OPS_ECOM', 'Operations Director'),
            ('HEAD_PERFORMANCE', 'Head of Performance Marketing'),
            ('HEAD_BRAND_MKT', 'Head of Brand Marketing'),
            ('HEAD_CRM_ECOM', 'Head of CRM & Loyalty'),
            ('DIR_MKT_ECOM', 'Marketing Director'),
            ('HEAD_SEO_ECOM', 'Head of SEO'),
            ('HEAD_CAT_MGMT', 'Head of Category Management'),
            ('DIR_COMMERCIAL', 'Commercial Director'),
            ('HEAD_PURCHASING', 'Head of Purchasing / Procurement'),
            ('HEAD_MARKETPLACE', 'Head of Marketplaces'),
            ('HEAD_PROD_ECOM', 'Head of Product'),
            ('DIR_ECOM_SALES', 'Director of E-commerce'),
            ('HEAD_UX_RESEARCH', 'Head of UX Research'),
            ('HEAD_CONVERSION', 'Head of CRO'),
            ('HEAD_ENG_ECOM', 'Head of Engineering'),
            ('HEAD_DATA_ANALYTICS', 'Head of Data & Analytics'),
            ('HEAD_ERP_CRM', 'Head of Business Systems (ERP/CRM/1C/SAP)'),
            ('HEAD_IT_INFRA', 'Head of IT Infrastructure'),
            ('HEAD_CS', 'Head of Customer Service'),
            ('HEAD_LOSS_PREV', 'Head of Loss Prevention'),
            ('HEAD_PAYMENTS', 'Head of Payments (E-com)'),
        ],
        'Management': [
            ('MGR_WAREHOUSE', 'Warehouse Manager'),
            ('MGR_INVENTORY', 'Inventory Manager'),
            ('MGR_LOGISTICS', 'Logistics Manager'),
            ('TL_DELIVERY', 'Delivery Team Lead'),
            ('MGR_PROCUREMENT', 'Procurement Manager'),
            ('MGR_CATEGORY', 'Category Manager'),
            ('MGR_MARKETPLACE', 'Marketplace Manager'),
            ('MGR_PRICING', 'Pricing Manager'),
            ('MGR_SALES_ECOM', 'E-commerce Sales Manager'),
            ('TL_PERFORMANCE', 'Performance Team Lead'),
            ('MGR_CRM_ECOM', 'CRM Manager'),
            ('TL_SEO_ECOM', 'SEO Team Lead'),
            ('MGR_SMM_ECOM', 'SMM Manager'),
            ('MGR_AFF_ECOM', 'Affiliate Manager'),
            ('MGR_PROD_ECOM', 'Product Manager'),
            ('MGR_PROJ_ECOM', 'Project Manager'),
            ('TL_UXUI_ECOM', 'UX/UI Team Lead'),
            ('MGR_CONTENT_ECOM', 'Content Manager'),
            ('TL_SUPPORT_ECOM', 'Support Team Lead'),
            ('MGR_CX', 'Customer Experience Manager'),
            ('MGR_RETURNS', 'Returns Manager'),
            ('TL_DEV_ECOM', 'Development Team Lead'),
            ('TL_QA_ECOM', 'QA Team Lead'),
            ('TL_DATA_ECOM', 'Analytics Team Lead'),
        ],
        'Senior': [
            ('SNR_LOG_MGR', 'Senior Logistics Manager'),
            ('SNR_SUPPLY_SPEC', 'Senior Supply Chain Specialist'),
            ('SNR_WH_OPS', 'Senior Warehouse Operations Manager'),
            ('SNR_PROCUREMENT', 'Senior Procurement Specialist'),
            ('SNR_PERF_MKT', 'Senior Performance Manager'),
            ('SNR_CRM_LOYALTY', 'Senior CRM & Loyalty Specialist'),
            ('SNR_SEO_ECOM', 'Senior SEO Specialist'),
            ('SNR_AFF_ECOM', 'Senior Affiliate Manager'),
            ('SNR_RETENTION', 'Senior Retention Specialist'),
            ('SNR_CAT_MGR', 'Senior Category Manager'),
            ('SNR_MARKETPLACE_SPEC', 'Senior Marketplace Specialist'),
            ('SNR_PRICING_MGR', 'Senior Pricing & Yield Manager'),
            ('SNR_COMM_SPEC', 'Senior Commercial Specialist'),
            ('SNR_PROD_ECOM', 'Senior Product Manager'),
            ('SNR_UXUI_ECOM', 'Senior UI/UX Designer'),
            ('SNR_CRO_SPEC', 'Senior Conversion Specialist'),
            ('SNR_UX_RESEARCH', 'Senior UX Researcher'),
            ('SNR_BE_ECOM', 'Senior Backend Developer'),
            ('SNR_FE_ECOM', 'Senior Frontend Developer'),
            ('SNR_SOL_ARCH', 'Senior Solutions Architect'),
            ('SNR_QA_AUTO', 'Senior QA Automation'),
            ('SNR_ECOM_ANALYST', 'Senior E-commerce Analyst'),
            ('SNR_BI_DEV', 'Senior BI Developer'),
            ('SNR_DATA_SCI_ECOM', 'Senior Data Scientist'),
        ],
        'Specialist': [
            ('SPEC_LOGISTICS', 'Logistics Specialist'),
            ('SPEC_INVENTORY', 'Inventory Analyst'),
            ('SPEC_FULFILLMENT', 'Fulfillment Specialist'),
            ('SPEC_PROCUREMENT', 'Procurement Specialist'),
            ('SPEC_SUPPLY_CHAIN', 'Supply Chain Planner'),
            ('SPEC_PERF_MKT', 'Performance Marketing Specialist'),
            ('SPEC_CRM_ECOM', 'CRM Specialist'),
            ('SPEC_SEO_ECOM', 'SEO Specialist'),
            ('SPEC_EMAIL_MKT', 'Email Marketer'),
            ('SPEC_SMM_ECOM', 'SMM Specialist'),
            ('SPEC_CATEGORY', 'Category Specialist'),
            ('SPEC_MARKETPLACE', 'Marketplace Specialist'),
            ('SPEC_PRICING', 'Pricing Analyst'),
            ('SPEC_CATALOG_MGR', 'Catalog Manager'),
            ('SPEC_PROD_ECOM', 'Product Specialist'),
            ('SPEC_CONTENT_MGR', 'Content Specialist'),
            ('SPEC_UXUI_DESIGN', 'UX/UI Designer'),
            ('SPEC_COPY_ECOM', 'E-commerce Copywriter'),
            ('SPEC_BE_DEV', 'Backend Developer'),
            ('SPEC_FE_DEV', 'Frontend Developer'),
            ('SPEC_QA_ECOM', 'QA Engineer'),
            ('SPEC_DATA_ANALYST', 'Data Analyst'),
            ('SPEC_SUPPORT_ECOM', 'Customer Support Specialist'),
            ('SPEC_RETURNS', 'Claims & Returns Specialist'),
            ('SPEC_CX_COORDINATOR', 'Customer Experience Coordinator'),
        ],
        'Junior / Entry': [
            ('JUN_LOG_ASST', 'Junior Logistics Assistant'),
            ('JUN_INV_MONITOR', 'Inventory Monitor'),
            ('JUN_SHIP_CORD', 'Shipping Coordinator'),
            ('JUN_PROCURE_ASST', 'Procurement Assistant'),
            ('JUN_MB_ECOM', 'Junior Media Buyer (E-com)'),
            ('JUN_CRM_ASST', 'Junior CRM Assistant'),
            ('JUN_SEO_ASST', 'Junior SEO Specialist'),
            ('JUN_SMM_ECOM', 'Junior SMM / Community'),
            ('JUN_CONTENT_ECOM', 'Junior Content Manager'),
            ('JUN_PHOTO_EDIT', 'Junior Photo Retoucher'),
            ('JUN_CARD_MGR', 'Marketplace Card Manager'),
            ('JUN_COPY_ECOM', 'Junior Copywriter'),
            ('JUN_DEV_ECOM', 'Junior Web Developer'),
            ('JUN_QA_MANUAL', 'Junior QA Tester'),
            ('JUN_DATA_ECOM', 'Junior Data Entry'),
            ('JUN_ANALYST_ASST', 'Analytics Assistant'),
            ('JUN_SUPPORT_ECOM', 'Customer Support Agent'),
            ('JUN_CLAIM_ASST', 'Claims Assistant'),
            ('JUN_MODERATOR_ECOM', 'Review Moderator'),
        ],
    },
    'FinTech': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO', 'Chief Operating Officer'),
            ('CFO_FIN', 'Chief Financial Officer'),
            ('CSO_FIN', 'Chief Strategy Officer'),
            ('CCO_FIN', 'Chief Compliance Officer'),
            ('CRO_FIN', 'Chief Risk Officer'),
            ('CLO_FIN', 'Chief Legal Officer'),
            ('CAMLO', 'Chief AML Officer'),
            ('CTO_FIN', 'Chief Technology Officer'),
            ('CPO_FIN', 'Chief Product Officer'),
            ('CISO_FIN', 'Chief Information Security Officer'),
            ('CDO_FIN', 'Chief Data Officer'),
            ('CMO_FIN', 'Chief Marketing Officer'),
            ('CBDO_FIN', 'Chief Business Development Officer'),
            ('CRO_REVENUE', 'Chief Revenue Officer'),
        ],
        'Head of / Director': [
            ('HEAD_COMP_FIN', 'Head of Compliance'),
            ('DIR_RISK_FIN', 'Risk Director'),
            ('HEAD_AML_FIN', 'Head of AML / KYC'),
            ('DIR_LEGAL_FIN', 'Legal Director'),
            ('HEAD_REG_AFFAIRS', 'Head of Regulatory Affairs'),
            ('DIR_PROD_FIN', 'Product Director'),
            ('HEAD_CARDS', 'Head of Cards'),
            ('HEAD_LENDING', 'Head of Lending'),
            ('HEAD_GROWTH_FIN', 'Head of Growth'),
            ('HEAD_INVEST_PROD', 'Head of Investment Products'),
            ('HEAD_PAY_FIN', 'Head of Payments'),
            ('DIR_TREASURY_FIN', 'Treasury Director'),
            ('HEAD_ACQUIRING', 'Head of Acquiring'),
            ('HEAD_BILLING_FIN', 'Head of Billing & Settlement'),
            ('DIR_MKT_FIN', 'Marketing Director'),
            ('HEAD_BD_FIN', 'Head of Business Development'),
            ('HEAD_PARTNERSHIPS', 'Head of Strategic Partnerships'),
            ('HEAD_ENG_FIN', 'Head of Engineering'),
            ('DIR_DATA_FIN', 'Director of Data Science'),
            ('HEAD_ARCHITECT_FIN', 'Head of Solution Architecture'),
            ('DIR_INFOSEC', 'Director of Information Security'),
            ('DIR_OPS_FIN', 'Operations Director'),
            ('HEAD_CS_FIN', 'Head of Customer Success'),
            ('HEAD_CX_FIN', 'Head of Customer Experience'),
        ],
        'Management': [
            ('MGR_COMP_FIN', 'Compliance Manager'),
            ('MGR_AML_KYC', 'AML / KYC Manager'),
            ('MGR_RISK_FIN', 'Risk Manager'),
            ('MGR_FRAUD_FIN', 'Fraud Manager'),
            ('MLRO_MGR', 'Money Laundering Reporting Officer'),
            ('MGR_PROD_PAY', 'Payments Product Manager'),
            ('MGR_PROD_BANK', 'Banking Product Manager'),
            ('MGR_PROD_LOAN', 'Lending Product Manager'),
            ('MGR_PROJ_FIN', 'FinTech Project Manager'),
            ('MGR_TREASURY_FIN', 'Treasury Manager'),
            ('MGR_PAYMENTS_FIN', 'Payments Manager'),
            ('MGR_BILLING_FIN', 'Billing Manager'),
            ('MGR_SETTLEMENT', 'Settlement Manager'),
            ('TL_BE_FIN', 'Backend Tech Lead'),
            ('TL_FE_FIN', 'Frontend Tech Lead'),
            ('TL_QA_FIN', 'QA Team Lead'),
            ('TL_DATA_FIN', 'Data Lead'),
            ('MGR_BD_FIN', 'Business Development Manager'),
            ('MGR_PARTNERSHIPS_FIN', 'Partnerships Manager'),
            ('TL_MB_FIN', 'Media Buying Team Lead'),
            ('TL_SUPPORT_FIN', 'Support Team Lead'),
            ('MGR_CX_FIN', 'Customer Experience Manager'),
        ],
        'Senior': [
            ('SNR_BE_FIN', 'Senior Backend Developer'),
            ('SNR_ARCH_FIN', 'Senior Solution Architect'),
            ('SNR_FE_FIN', 'Senior Frontend Developer'),
            ('SNR_IOS_FIN', 'Senior iOS Developer'),
            ('SNR_ANDR_FIN', 'Senior Android Developer'),
            ('SNR_SRE_FIN', 'Senior Site Reliability Engineer'),
            ('SNR_SEC_FIN', 'Senior InfoSec Engineer'),
            ('SNR_RISK_FIN', 'Senior Risk Manager'),
            ('SNR_COMP_FIN', 'Senior Compliance Officer'),
            ('SNR_AML_KYC', 'Senior AML/KYC Specialist'),
            ('SNR_FRAUD_FIN', 'Senior Anti-Fraud Analyst'),
            ('SNR_DS_FIN', 'Senior Data Scientist'),
            ('SNR_QUANT_FIN', 'Senior Quantitative Analyst'),
            ('SNR_BI_FIN', 'Senior BI Analyst'),
            ('SNR_DATA_ENG_FIN', 'Senior Data Engineer'),
            ('SNR_PROD_PAY', 'Senior Payments Product Manager'),
            ('SNR_PROD_BANK', 'Senior Banking Product Manager'),
            ('SNR_UXUI_FIN', 'Senior UX/UI Designer'),
            ('SNR_UX_RES_FIN', 'Senior UX Researcher'),
            ('SNR_TREASURY_FIN', 'Senior Treasury Manager'),
            ('SNR_FIN_ANALYST', 'Senior Financial Analyst'),
        ],
        'Specialist': [
            ('SPEC_BE_FIN', 'Backend Developer'),
            ('SPEC_FE_FIN', 'Frontend Developer'),
            ('SPEC_IOS_FIN', 'iOS Developer'),
            ('SPEC_ANDROID_FIN', 'Android Developer'),
            ('SPEC_QA_FIN', 'QA Engineer (FinTech)'),
            ('SPEC_COMP_FIN', 'Compliance Specialist'),
            ('SPEC_AML_KYC', 'AML / KYC Specialist'),
            ('SPEC_RISK_FIN', 'Risk Specialist'),
            ('SPEC_FRAUD_FIN', 'Anti-Fraud Specialist'),
            ('SPEC_PAYMENTS', 'Payments Specialist'),
            ('SPEC_TREASURY', 'Treasury Specialist'),
            ('SPEC_BILLING', 'Billing Specialist'),
            ('SPEC_SETTLEMENT', 'Settlement Specialist'),
            ('SPEC_PROD_FIN', 'Product Manager'),
            ('SPEC_UXUI_FIN', 'UX/UI Designer'),
            ('SPEC_PROJ_FIN', 'Project Manager'),
            ('SPEC_DATA_FIN', 'Data Analyst'),
            ('SPEC_FIN_ANALYST', 'Financial Analyst'),
            ('SPEC_BI_ANALYST', 'BI Analyst'),
            ('SPEC_SUPPORT_FIN', 'Customer Support Specialist'),
            ('SPEC_BD_FIN', 'Business Development Specialist'),
            ('SPEC_AM_FIN', 'Account Manager'),
        ],
        'Junior / Entry': [
            ('JUN_KYC_FIN', 'Junior KYC Analyst'),
            ('JUN_AML_MONITOR', 'AML Monitor'),
            ('JUN_COMP_ASST', 'Compliance Assistant'),
            ('JUN_VERIF_FIN', 'Verification Officer'),
            ('JUN_PAY_ASST', 'Junior Payments Assistant'),
            ('JUN_BILLING_ASST', 'Junior Billing Specialist'),
            ('JUN_DATA_FIN', 'Data Entry (Finance)'),
            ('JUN_OPS_FIN', 'Junior Operations Assistant'),
            ('JUN_DEV_FIN', 'Junior Developer'),
            ('JUN_QA_FIN', 'Junior QA Tester'),
            ('JUN_SQL_ANALYST', 'Junior Data Analyst'),
            ('JUN_BD_FIN', 'Junior Business Development'),
            ('JUN_AM_FIN', 'Junior Account Manager'),
            ('JUN_MKT_FIN', 'Junior Marketing Specialist'),
            ('JUN_SALES_FIN', 'Junior Sales Representative'),
            ('JUN_SUPPORT_FIN', 'Support Agent'),
            ('JUN_CLAIM_FIN', 'Junior Claims Agent'),
            ('JUN_HELP_DESK', 'Technical Support Assistant'),
        ],
    },
    'Nutra': {
        'C-Level': [
            ('CEO', 'Chief Executive Officer'),
            ('COO_NUTRA', 'Chief Operating Officer'),
            ('CFO_NUTRA', 'Chief Financial Officer'),
            ('CSO_NUTRA', 'Chief Strategy Officer'),
            ('CMO_NUTRA', 'Chief Marketing Officer'),
            ('CGO_NUTRA', 'Chief Growth Officer'),
            ('CBDO_NUTRA', 'Chief Business Development Officer'),
            ('CRO_NUTRA', 'Chief Revenue Officer'),
            ('CPO_OFFERS', 'Chief Product Officer'),
            ('CSCO_NUTRA', 'Chief Supply Chain Officer'),
            ('CPO_SOURCING', 'Chief Procurement Officer'),
            ('CLO_NUTRA', 'Chief Legal Officer'),
            ('CHRO_NUTRA', 'Chief Human Resources Officer'),
            ('CIO_NUTRA', 'Chief Information Officer'),
        ],
        'Head of / Director': [
            ('HEAD_MB_NUTRA', 'Head of Media Buying'),
            ('HEAD_AFF_NUTRA', 'Head of Affiliate'),
            ('DIR_MKT_NUTRA', 'Marketing Director'),
            ('HEAD_PERF_NUTRA', 'Head of Performance Marketing'),
            ('HEAD_UA_NUTRA', 'Head of User Acquisition'),
            ('DIR_PROD_NUTRA', 'Production Director'),
            ('HEAD_SOURCING', 'Head of Sourcing & Procurement'),
            ('HEAD_RD_NUTRA', 'Head of R&D (Nutra)'),
            ('HEAD_QUALITY', 'Head of Quality Control'),
            ('HEAD_CERT_REG', 'Head of Certification & Regulatory'),
            ('HEAD_CC_NUTRA', 'Head of Call Center'),
            ('DIR_SALES_NUTRA', 'Sales Director'),
            ('HEAD_TRAINING_CC', 'Head of CC Training & Quality'),
            ('HEAD_OUTSOURCE_CC', 'Head of External Call Centers'),
            ('DIR_OPS_NUTRA', 'Operations Director'),
            ('HEAD_LOG_NUTRA', 'Head of Logistics'),
            ('HEAD_SUPPLY_CHAIN', 'Head of Supply Chain'),
            ('HEAD_FULFILLMENT', 'Head of Fulfillment'),
            ('HEAD_LAST_MILE', 'Head of Last Mile Delivery'),
            ('HEAD_OFFER_MGMT', 'Head of Offer Management'),
            ('DIR_CREATIVE', 'Creative Director (Nutra)'),
            ('HEAD_WEB_DEV', 'Head of Web Development'),
            ('HEAD_CRM_RET', 'Head of CRM & Retention'),
            ('HEAD_LEGAL_NUTRA', 'Head of Legal & Compliance'),
            ('HEAD_FIN_NUTRA', 'Head of Finance'),
        ],
        'Management': [
            ('TL_MB_FB', 'Media Buying Team Lead (FB)'),
            ('TL_MB_GOOGLE', 'Media Buying Team Lead (Google)'),
            ('TL_MB_NATIVE', 'Media Buying Team Lead (Native)'),
            ('TL_MB_TIKTOK', 'Media Buying Team Lead (TikTok)'),
            ('TL_AFF_NUTRA', 'Affiliate Team Lead'),
            ('MGR_INFLUENCER_NUTRA', 'Influencer Marketing Manager'),
            ('MGR_CC_OPS', 'Call Center Operations Manager'),
            ('TL_CC_SALES', 'Call Center Sales Team Lead'),
            ('MGR_CC_QUALITY', 'Call Center Quality Manager'),
            ('MGR_OUTSOURCE_CC', 'Outsource CC Manager'),
            ('MGR_TRAINING_CC', 'CC Training Manager'),
            ('MGR_PROCUREMENT', 'Procurement Manager'),
            ('MGR_SOURCING_ASIA', 'Sourcing Manager'),
            ('MGR_WAREHOUSE', 'Warehouse Manager'),
            ('MGR_LOG_NUTRA', 'Logistics Manager'),
            ('MGR_INVENTORY', 'Inventory Control Manager'),
            ('MGR_OFFER_NUTRA', 'Offer Manager'),
            ('TL_DESIGN_NUTRA', 'Creative Team Lead'),
            ('TL_WEB_DEV_NUTRA', 'Web Dev Team Lead'),
            ('MGR_CRM_NUTRA', 'CRM / Retention Manager'),
            ('MGR_CONTENT_NUTRA', 'Content Manager'),
            ('MGR_PROJECT_NUTRA', 'Project Manager'),
            ('MGR_COMPLIANCE_NUTRA', 'Compliance Manager'),
            ('MGR_FIN_OPS', 'Financial Operations Manager'),
            ('MGR_AD_TECH', 'AdTech Manager'),
        ],
        'Senior': [
            ('SNR_MB_FB_NUTRA', 'Senior Media Buyer (FB)'),
            ('SNR_MB_GG_NUTRA', 'Senior Media Buyer (Google)'),
            ('SNR_MB_NAT_NUTRA', 'Senior Media Buyer (Native)'),
            ('SNR_MB_TT_NUTRA', 'Senior Media Buyer (TikTok)'),
            ('SNR_AFF_NUTRA', 'Senior Affiliate Manager'),
            ('SNR_COPY_NUTRA', 'Senior Copywriter'),
            ('SNR_MOTION_NUTRA', 'Senior Motion Designer'),
            ('SNR_WEB_DEV_NUTRA', 'Senior Web Developer'),
            ('SNR_CRO_SPEC', 'Senior Conversion Specialist'),
            ('SNR_SOURCING_SPEC', 'Senior Sourcing Specialist'),
            ('SNR_RD_NUTRA', 'Senior R&D Specialist'),
            ('SNR_QC_NUTRA', 'Senior Quality Control'),
            ('SNR_REG_SPEC', 'Senior Regulatory & Cert Specialist'),
            ('SNR_CC_ANALYST', 'Senior Call Center Analyst'),
            ('SNR_SCRIPT_WRITER', 'Senior Sales Script Writer'),
            ('SNR_RETENTION_SPEC', 'Senior Retention Specialist'),
            ('SNR_LOG_SPEC', 'Senior Logistics Specialist'),
            ('SNR_SUPPLY_PLAN', 'Senior Supply Chain Planner'),
            ('SNR_FULFILL_MGR', 'Senior Fulfillment Specialist'),
            ('SNR_COMP_OFFICER', 'Senior Compliance Officer'),
            ('SNR_DATA_ANALYST', 'Senior Data Analyst'),
        ],
        'Specialist': [
            ('SPEC_MB_FB', 'Media Buyer (FB/Instagram)'),
            ('SPEC_MB_GG', 'Media Buyer (Google Ads)'),
            ('SPEC_MB_TT', 'Media Buyer (TikTok)'),
            ('SPEC_MB_NATIVE', 'Media Buyer (Native Ads)'),
            ('SPEC_AFF_NUTRA', 'Affiliate Manager (Nutra)'),
            ('SPEC_INFLUENCER', 'Influencer Specialist'),
            ('SPEC_COPY_NUTRA', 'Copywriter (Nutra)'),
            ('SPEC_DESIGN_NUTRA', 'Creative Designer'),
            ('SPEC_VIDEO_NUTRA', 'Video Editor / Motion'),
            ('SPEC_WEB_DEV_NUTRA', 'Web Developer'),
            ('SPEC_LOCALIZER', 'Content Localizer'),
            ('SPEC_CC_SUPERVISOR', 'Call Center Supervisor'),
            ('SPEC_CC_QUALITY', 'CC Quality Specialist'),
            ('SPEC_CC_TRAINER', 'Call Center Trainer'),
            ('SPEC_RETENTION', 'Retention Specialist'),
            ('SPEC_SCRIPT_NUTRA', 'Script Writer'),
            ('SPEC_LOG_NUTRA', 'Logistics Specialist'),
            ('SPEC_PROCUREMENT', 'Procurement Specialist'),
            ('SPEC_WAREHOUSE', 'Warehouse Specialist'),
            ('SPEC_INV_ANALYST', 'Inventory Analyst'),
            ('SPEC_FULFILLMENT', 'Fulfillment Specialist'),
            ('SPEC_AD_TECH', 'Technical Specialist (Tracking)'),
            ('SPEC_DATA_ANALYST', 'Data Analyst'),
            ('SPEC_SOURCING', 'Sourcing Specialist'),
            ('SPEC_QC_NUTRA', 'Quality Control (Product)'),
            ('SPEC_REGULATORY', 'Regulatory Affairs Specialist'),
            ('SPEC_SUPPORT_NUTRA', 'Customer Support'),
            ('SPEC_REFUND_MGR', 'Refund / Chargeback Manager'),
        ],
        'Junior / Entry': [
            ('JUN_MB_NUTRA', 'Junior Media Buyer'),
            ('FARMER_FB_NUTRA', 'Account Farmer (FB/Google)'),
            ('JUN_AFF_NUTRA', 'Junior Affiliate Manager'),
            ('JUN_UA_ASST', 'User Acquisition Assistant'),
            ('JUN_ADS_STAGER', 'Ad Stager'),
            ('JUN_COPY_NUTRA', 'Junior Copywriter'),
            ('JUN_DESIGN_NUTRA', 'Junior Graphic Designer'),
            ('JUN_VIDEO_ASST', 'Video Production Assistant'),
            ('JUN_WEB_ASST', 'Junior Web Assistant'),
            ('JUN_CONTENT_MOD', 'Ad Content Moderator'),
            ('JUN_CC_AGENT', 'Call Center Agent'),
            ('JUN_CC_RECOVERY', 'Recovery Agent'),
            ('JUN_CC_VALIDATOR', 'Lead Validator'),
            ('JUN_CC_NIGHT', 'Night Shift Operator'),
            ('JUN_LOG_ASST', 'Junior Logistics Assistant'),
            ('JUN_WH_PACKER', 'Warehouse Packer'),
            ('JUN_WH_PICKER', 'Warehouse Picker'),
            ('JUN_DATA_ENTRY', 'Data Entry Specialist'),
            ('JUN_PROCURE_ASST', 'Procurement Assistant'),
            ('JUN_TECH_SETTER', 'Tech Setter'),
            ('JUN_SUPPORT_NUTRA', 'Support Agent'),
            ('JUN_QA_TESTER', 'Junior Manual Tester'),
        ],
    },
    'Other': {
        'C-Level': [
            ('CHRO', 'Chief Human Resources Officer'),
            ('CPO_PEOPLE', 'Chief People Officer'),
            ('CLO_CORP', 'Chief Learning Officer'),
            ('CDIO', 'Chief Diversity & Inclusion Officer'),
            ('CLO_LEGAL', 'Chief Legal Officer'),
            ('CCO_COMP', 'Chief Compliance Officer'),
            ('CDPO', 'Chief Data Privacy Officer'),
            ('CGOV', 'Chief Governance Officer'),
            ('CFO_GROUP', 'Chief Financial Officer'),
            ('CAE', 'Chief Audit Executive'),
            ('CTO_TAX', 'Chief Tax Officer'),
            ('CIO_INVEST', 'Chief Investment Officer'),
            ('CAO_CORP', 'Chief Administrative Officer'),
            ('CISO_CORP', 'Chief Information Security Officer'),
            ('CSO_PHYSICAL', 'Chief Security Officer'),
            ('CIO_CORP', 'Chief Information Officer'),
            ('CCOMMO', 'Chief Communications Officer'),
            ('CSO_ESG', 'Chief Sustainability Officer'),
            ('CIRO', 'Chief Investor Relations Officer'),
            ('CBEO', 'Chief Brand Experience Officer'),
        ],
        'Head of / Director': [
            ('HEAD_RECRUITMENT', 'Head of Talent Acquisition'),
            ('DIR_HR', 'HR Director'),
            ('HEAD_LD', 'Head of L&D'),
            ('HEAD_COMP_BEN', 'Head of Comp & Ben'),
            ('HEAD_PEOPLE_OPS', 'Head of People Operations'),
            ('DIR_TALENT_MGMT', 'Director of Talent Management'),
            ('DIR_FINANCE', 'Finance Director'),
            ('HEAD_ACCOUNTING', 'Head of Accounting'),
            ('HEAD_FPA', 'Head of FP&A'),
            ('HEAD_TREASURY', 'Head of Treasury'),
            ('HEAD_TAX_CORP', 'Head of Tax'),
            ('HEAD_INTERNAL_AUDIT', 'Head of Internal Audit'),
            ('DIR_LEGAL', 'Legal Director'),
            ('HEAD_COMPLIANCE', 'Head of Corporate Compliance'),
            ('HEAD_IP', 'Head of IP'),
            ('DIR_PRIVACY', 'Director of Data Privacy'),
            ('HEAD_CORP_SECRETARY', 'Head of Corporate Secretary'),
            ('HEAD_IT_INFRA', 'Head of IT Infrastructure'),
            ('DIR_INFOSEC_CORP', 'Director of InfoSec'),
            ('HEAD_CORP_SYSTEMS', 'Head of Corporate Systems'),
            ('DIR_PHYS_SECURITY', 'Director of Corporate Security'),
            ('HEAD_PR_COMMS', 'Head of PR & Comms'),
            ('HEAD_INTERNAL_COMMS', 'Head of Internal Communications'),
            ('HEAD_GR', 'Head of Government Relations'),
            ('HEAD_BRAND_EMP', 'Head of Employer Branding'),
            ('HEAD_PROCUREMENT', 'Head of Indirect Procurement'),
            ('HEAD_FACILITIES', 'Head of Facilities'),
            ('DIR_TRAVEL', 'Director of Corporate Travel'),
            ('HEAD_ESG_SUSTAIN', 'Head of ESG & Sustainability'),
        ],
        'Management': [
            ('HR_MGR_CORP', 'HR Manager'),
            ('RECRUITMENT_MGR', 'Recruitment Manager'),
            ('TA_MANAGER', 'Talent Acquisition Manager'),
            ('COMP_BEN_MGR', 'Comp & Ben Manager'),
            ('LD_MANAGER', 'L&D Manager'),
            ('HRBP_MGR', 'HR Business Partner'),
            ('PAYROLL_MGR', 'Payroll Manager'),
            ('ACCOUNTING_MGR', 'Accounting Manager'),
            ('TAX_MGR_CORP', 'Tax Manager'),
            ('FPA_MANAGER', 'FP&A Manager'),
            ('TREASURY_MGR', 'Treasury Manager'),
            ('BILLING_MGR_CORP', 'Billing Manager'),
            ('AUDIT_MGR_INTERNAL', 'Internal Audit Manager'),
            ('LEGAL_MGR_CORP', 'Legal Manager'),
            ('COMPLIANCE_MGR_CORP', 'Compliance Manager'),
            ('CONTRACT_MGR', 'Contract Manager'),
            ('PRIVACY_MGR', 'Data Privacy Manager'),
            ('IT_OPS_MGR_CORP', 'IT Operations Manager'),
            ('SYS_ADMIN_TL', 'Systems Administration Team Lead'),
            ('INFOSEC_MGR_CORP', 'Information Security Manager'),
            ('CORP_SECURITY_MGR', 'Corporate Security Manager'),
            ('IT_SERVICE_MGR', 'IT Service Manager (ITSM)'),
            ('OFFICE_MGR_CORP', 'Office Manager'),
            ('FACILITY_MGR_CORP', 'Facility Manager'),
            ('PROCUREMENT_MGR_CORP', 'Procurement Manager'),
            ('TRAVEL_MGR_CORP', 'Corporate Travel Manager'),
            ('ADMIN_PROJECT_MGR', 'Administrative Project Manager'),
            ('PR_MGR_CORP', 'PR Manager'),
            ('INTERNAL_COMMS_MGR', 'Internal Communications Manager'),
            ('EB_MANAGER', 'Employer Branding Manager'),
            ('EVENT_MGR_CORP', 'Corporate Event Manager'),
        ],
        'Senior': [
            ('SNR_RECRUITER_CORP', 'Senior Recruiter'),
            ('SNR_HRBP_CORP', 'Senior HR Business Partner'),
            ('SNR_COMP_BEN', 'Senior Comp & Ben Specialist'),
            ('SNR_LD_SPEC', 'Senior L&D Specialist'),
            ('SNR_TALENT_SOURCER', 'Senior Talent Sourcer'),
            ('SNR_PAYROLL_SPEC', 'Senior Payroll Specialist'),
            ('SNR_ACCOUNTANT_CORP', 'Senior Accountant'),
            ('SNR_FIN_ANALYST_CORP', 'Senior Financial Analyst'),
            ('SNR_TAX_CONSULT', 'Senior Tax Consultant'),
            ('SNR_TREASURY_SPEC', 'Senior Treasury Specialist'),
            ('SNR_INTERNAL_AUDITOR', 'Senior Internal Auditor'),
            ('SNR_LEGAL_COUNSEL', 'Senior Legal Counsel'),
            ('SNR_COMP_OFFICER', 'Senior Compliance Officer'),
            ('SNR_IP_LAWYER', 'Senior IP Lawyer'),
            ('SNR_PRIVACY_SPEC', 'Senior Data Privacy Specialist'),
            ('SNR_LITIGATION_LAWYER', 'Senior Litigation Lawyer'),
            ('SNR_SYS_ADMIN_CORP', 'Senior System Administrator'),
            ('SNR_NETWORK_ENG', 'Senior Network Engineer'),
            ('SNR_INFOSEC_SPEC', 'Senior InfoSec Specialist'),
            ('SNR_IT_SUPPORT_SPEC', 'Senior IT Support Specialist'),
            ('SNR_CORP_SECURITY', 'Senior Corporate Security Specialist'),
            ('SNR_PR_SPECIALIST', 'Senior PR Specialist'),
            ('SNR_INT_COMMS', 'Senior Internal Comms Specialist'),
            ('SNR_EB_SPECIALIST', 'Senior Employer Branding Specialist'),
            ('SNR_COPY_CORP', 'Senior Corporate Copywriter'),
            ('SNR_PROCURE_SPEC', 'Senior Procurement Specialist'),
            ('SNR_FACILITY_SPEC', 'Senior Facility Specialist'),
            ('SNR_TRAVEL_MGR', 'Senior Corporate Travel Specialist'),
            ('SNR_OFFICE_ADMIN', 'Senior Office Administrator'),
        ],
        'Specialist': [
            ('SPEC_RECRUITER_CORP', 'Recruiter'),
            ('SPEC_HR_CORP', 'HR Specialist'),
            ('SPEC_COMP_BEN_SPEC', 'Comp & Ben Specialist'),
            ('SPEC_TRAINING_CORP', 'Training & Development Specialist'),
            ('SPEC_SOURCER_CORP', 'Talent Sourcer'),
            ('SPEC_PAYROLL_SPEC', 'Payroll Specialist'),
            ('SPEC_ACCOUNTANT_CORP', 'Accountant'),
            ('SPEC_FIN_ANALYST', 'Financial Analyst'),
            ('SPEC_TAX_SPEC', 'Tax Specialist'),
            ('SPEC_TREASURY_CORP', 'Treasury Specialist'),
            ('SPEC_BILLING_CORP', 'Billing Specialist'),
            ('SPEC_AUDITOR_INTERNAL', 'Internal Auditor'),
            ('SPEC_LAWYER_CORP', 'Corporate Lawyer'),
            ('SPEC_COMP_SPEC', 'Compliance Specialist'),
            ('SPEC_CONTRACT_SPEC', 'Contract Specialist'),
            ('SPEC_PRIVACY_SPEC', 'Data Privacy Specialist'),
            ('SPEC_PARALEGAL', 'Paralegal'),
            ('SPEC_SYS_ADMIN_CORP', 'System Administrator'),
            ('SPEC_IT_SUPPORT', 'IT Support Engineer'),
            ('SPEC_NETWORK_SPEC', 'Network Specialist'),
            ('SPEC_INFOSEC_SPEC', 'Information Security Specialist'),
            ('SPEC_IT_ASSET_MGR', 'IT Asset Manager'),
            ('SPEC_PR_CORP', 'PR Specialist'),
            ('SPEC_INT_COMMS', 'Internal Comms Specialist'),
            ('SPEC_EB_SPECIALIST', 'Employer Branding Specialist'),
            ('SPEC_EVENT_CORP', 'Event Coordinator'),
            ('SPEC_COPY_CORP', 'Corporate Copywriter'),
            ('SPEC_OFFICE_ADMIN', 'Office Administrator'),
            ('SPEC_PROCURE_SPEC', 'Procurement Specialist'),
            ('SPEC_FACILITY_SPEC', 'Facility Specialist'),
            ('SPEC_TRAVEL_COORD', 'Travel Coordinator'),
            ('SPEC_RECEPTIONIST', 'Receptionist'),
        ],
        'Junior / Entry': [
            ('JUN_RECRUITER_CORP', 'Junior Recruiter'),
            ('RECRUITMENT_RES', 'Recruitment Researcher'),
            ('JUN_HR_ASST', 'Junior HR Assistant'),
            ('JUN_TA_ASST', 'Talent Acquisition Assistant'),
            ('JUN_ACCOUNTANT_CORP', 'Junior Accountant'),
            ('FINANCE_ASST', 'Finance Assistant'),
            ('JUN_PAYROLL_ASST', 'Junior Payroll Assistant'),
            ('JUN_BILLING_ASST', 'Junior Billing Assistant'),
            ('DATA_ENTRY_FIN', 'Data Entry Specialist (Finance)'),
            ('JUN_LAWYER_CORP', 'Junior Lawyer'),
            ('COMPLIANCE_ASST', 'Compliance Assistant'),
            ('DOC_CONTROLLER', 'Document Controller'),
            ('LEGAL_ASST_CORP', 'Legal Assistant'),
            ('IT_HELP_DESK', 'IT Help Desk Technician (L1)'),
            ('JUN_SYS_ADMIN', 'Junior System Administrator'),
            ('IT_SUPPORT_ASST', 'IT Support Assistant'),
            ('JUN_INFOSEC_ASST', 'Junior InfoSec Assistant'),
            ('JUN_PR_SPECIALIST', 'Junior PR Specialist'),
            ('INTERNAL_COMMS_ASST', 'Internal Comms Assistant'),
            ('JUN_EVENT_COORD', 'Junior Event Coordinator'),
            ('SOCIAL_MEDIA_ASST', 'Social Media Assistant (Internal)'),
            ('OFFICE_ASST_CORP', 'Office Assistant'),
            ('JUN_PROCURE_ASST', 'Procurement Assistant'),
            ('TRAVEL_ASST_CORP', 'Travel Assistant'),
            ('JUN_FACILITY_ASST', 'Junior Facility Assistant'),
            ('MAILROOM_SPEC', 'Mailroom Specialist'),
        ],
    },
}
